### ISSUE TITLE
gibberish output 

### ISSUE THREAD

**Issue by A-AFTAHI** [reddr/LibScout#3]
i tried to create a profile and try to find a match but i got this (ps the apk used and the second phase use the given retrofit library)

 java -jar ../build/LibScout.jar -o profile -a ../lib/android-23.jar -x /root/Downloads/retrofit.xml /root/Downloads/retrofit-2.4.0.jar
10:18:48,756 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:18:48,757 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:18:48,757 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
10:18:48,763 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Setting up default configuration.
10:18:48,918 |-ERROR in ch.qos.logback.classic.joran.JoranConfigurator@5d22bbb7 - Could not open [./logging/logback.xml]. java.io.FileNotFoundException: ./logging/logback.xml (No such file or directory)
        at java.io.FileNotFoundException: ./logging/logback.xml (No such file or directory)
        at      at java.io.FileInputStream.open0(Native Method)
        at      at java.io.FileInputStream.open(FileInputStream.java:195)
        at      at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:75)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:68)
        at      at de.infsec.tpl.TplCLI.initLogging(Unknown Source)
        at      at de.infsec.tpl.TplCLI.main(Unknown Source)

 java -jar ../build/LibScout.jar -o match -a ../lib/android-23.jar /root/Downloads/dgi_proguard.apk
10:24:45,349 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:24:45,349 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:24:45,349 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
10:24:45,355 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Setting up default configuration.
10:24:45,514 |-ERROR in ch.qos.logback.classic.joran.JoranConfigurator@5d22bbb7 - Could not open [./logging/logback.xml]. java.io.FileNotFoundException: ./logging/logback.xml (No such file or directory)
        at java.io.FileNotFoundException: ./logging/logback.xml (No such file or directory)
        at      at java.io.FileInputStream.open0(Native Method)
        at      at java.io.FileInputStream.open(FileInputStream.java:195)
        at      at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:75)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:68)
        at      at de.infsec.tpl.TplCLI.initLogging(Unknown Source)
        at      at de.infsec.tpl.TplCLI.main(Unknown Source)

java.lang.ArrayIndexOutOfBoundsException: 636
        at android.content.res.StringBlock.getShort(Unknown Source)
        at android.content.res.StringBlock.getString(Unknown Source)
        at android.content.res.AXmlResourceParser.getName(Unknown Source)
        at de.infsec.tpl.manifest.ProcessManifest.loadClassesFromBinaryManifest(Unknown Source)
        at de.infsec.tpl.manifest.ProcessManifest$1.handleManifest(Unknown Source)
        at de.infsec.tpl.manifest.ProcessManifest.handleAndroidManifestFile(Unknown Source)
        at de.infsec.tpl.manifest.ProcessManifest.loadManifestFile(Unknown Source)
        at de.infsec.tpl.LibraryIdentifier.parseManifest(Unknown Source)
        at de.infsec.tpl.LibraryIdentifier.identifyLibraries(Unknown Source)
        at de.infsec.tpl.TplCLI.main(Unknown Source)

**Comment by A-AFTAHI** [comment]
i solved it i had a missing logback.xml file
