### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by yqbboy** [reddr/LibScout#31]
19:47:55 ERROR TplCLI                    : [FATAL EXCEPTION] analysis aborted: null 19:47:55 ERROR TplCLI                    : java.lang.NullPointerException 	at java.util.TreeMap.getEntry(TreeMap.java:347) 	at java.util.TreeMap.containsKey(TreeMap.java:232) 	at java.util.TreeSet.contains(TreeSet.java:234) 	at de.infsec.tpl.modules.libmatch.LibCodeUsage.checkUsage(LibCodeUsage.java:78) 	at de.infsec.tpl.modules.libmatch.LibraryIdentifier.identifyLibraries(LibraryIdentifier.java:204) 	at de.infsec.tpl.modules.libmatch.LibraryIdentifier.run(LibraryIdentifier.java:84) 	at de.infsec.tpl.TplCLI.main(TplCLI.java:141)

**Comment by reddr** [comment]
It seems that the TreeSet implementation throws a NPE if `contains()` is called with the `null` argument. This could be easily fixed by explicitly checking for `null`.

Could you please change LibCodeUsage.java:78 to
`if (rootpckg != null && !LibraryIdentifier.ambiguousRootPackages.contains(rootPckg) && !rootPckg2Lib.containsKey(rootPckg)) {`
and try again?
